### ISSUE TITLE
pullrequest.js doesn't execute when coming from the PR view of a repo

### ISSUE THREAD

**Issue by gholts** [Yatser/prettypullrequests#21]
If I'm looking at the list of pull requests, a `/pulls` URI, and I click on one, none of the collapse stuff shows up. One has to refresh the page when you're _on_ the PR to make that stuff show up.

This is because the transition to the PR happens via PJAX, so we probably need to add a listener for that or something.

@yatser I'd love to work on this, and I'm working on something else for this project right now, but in my own fork. Wanna give me full permissions and I can branch off your repo?

**Comment by Yatser** [comment]
Permission given. Note that the collapsing still works since the jquery selector is attached to the body selector first and will therefore update on dynamic elements, but... inserting custom html is a bit trickier. I think what we MIGHT have to do is a two step operation:
1) Add a listener for when the URL changes
2) When the URL changes, first check if we have already inserted the HTML, either via some dummy element that we insert just for the purpose of this check, or just by looking for the HTML that we insert, etc. If it's not there, insert it.

**Comment by gholts** [comment]
:+1: Thanks!

**Comment by Yatser** [comment]
@gholts this was fixed quite a while ago I just forgot to close the bug :+1:

**Comment by gholts** [comment]
Whoop!

**Comment by JeremybellEU** [comment]
I am still experiencing this bug. Inspecting using Chrome web tools provides the following message:
![image](https://cloud.githubusercontent.com/assets/5948271/9223283/f2ef0dae-40f8-11e5-9732-c9f4b2e737a5.png)

With corresponding code located at https://github.com/Yatser/prettypullrequests/blob/master/popup.js#L58

Steps to reproduce:
1. Open https://github.com/Yatser/prettypullrequests in a **new tab**.
2. Click the **Pull requests** button.
3. Click the **//Number// Closed** button.
4. Click on a pull request.
5. Open the plugin by clicking on the icon in the top bar.
6. Right click anywhere on the popup and inspect element.
7. Observe the generated error in the console.

An interesting observation is that if you go straight to the **Pull Requests** in a new tab, and following the instructions after step 2, the error is not generated.

**Comment by Yatser** [comment]
@JeremybellEU ahh ok, I think that's a fairly easy fix, I will look into it.
