### ISSUE TITLE
Unfolding folder hides highlight

### ISSUE THREAD

**Issue by JeremybellEU** [Yatser/prettypullrequests#26]
In the tree view, you can use the arrow keys to go through the list of folders. However, when you press `right`, unfolding a folder, the highlight is removed. When you press `right` again, it correctly goes to the first item in the unfolded folder. This is the correct behaviour, but the highlight that disappears is counterintuitive.

**Comment by Yatser** [comment]
Thanks, I'll look and see if there is something I can do. The tree view is using JSTree, I should be able to figure out what it is. Alternatively if you know what it is feel free to submit a PR!

**Comment by JeremybellEU** [comment]
According to the [changelog of JSTree](https://github.com/vakata/jstree/releases) the bug should be fixed in [3.0.9](https://github.com/vakata/jstree/releases/tag/3.0.9). Presumably the highlighting is fixed when updating to this version. It shouldn't generate any problems as it should be binary compatible.

**Comment by JeremybellEU** [comment]
P.S. The latest version released of JSTree is [3.2.0](https://github.com/vakata/jstree/releases/tag/3.2.0) so maybe that is even better.

**Comment by Yatser** [comment]
Unless I'm misunderstanding the problem, the newer JSTree didn't fix it. But let me explain what I see first...

In my experience, I have to click on a node first in order to use the arrow keys. That node highlights in a light blue. Then, if I use the arrow keys to open that node, an even lighter blue highlight follows my arrow key movements, but the original blue highlight stays where it is. 

Same thing happens with the newer JSTree, the original blue highlight is always staying on the last thing I clicked on.

Is this related to anything you're reporting? I know you mention your scenario happens when you are pressing the right arrow, which unfolds a node, but I don't think I am replicating the same problem because my original highlight stays there, but might be describing a different problem because my original highlighting is never on the right node, only the last one I clicked...

**Comment by JeremybellEU** [comment]
Initial state, folder `src` selected
![image](https://cloud.githubusercontent.com/assets/5948271/9223077/45b41f36-40f7-11e5-9f2f-65c65339f171.png)

**Click right-arrow ->**

![image](https://cloud.githubusercontent.com/assets/5948271/9223082/5692944a-40f7-11e5-847a-a3a514e57a80.png)
The `src` folder is still selected, but the gray background is behind `main`.

**Click right-arrow ->**

![image](https://cloud.githubusercontent.com/assets/5948271/9223093/7670f28e-40f7-11e5-82a9-e3716652bedd.png)
The `src` folder is still selected, but the gray background is removed. (internally it is at `main`).

**Click right-arrow ->**

![image](https://cloud.githubusercontent.com/assets/5948271/9223117/9ebb6620-40f7-11e5-80e9-bda8454d9312.png)
The `src` folder is still selected, the gray background appeared again and correctly at the `java` folder.

As you can see opening a folder (unfolding it, to show its contents) removes the gray background. However internally it still is there, as a new right arrow correctly goes to the first item in the unfolded folder.

**Comment by Yatser** [comment]
Gotcha, I'll update JSTree again and check if it solves that issue later today! Thanks for clarifying.

**Comment by JeremybellEU** [comment]
Any progress so far @Yatser ? Can I help you with anything?

**Comment by Yatser** [comment]
Hey @JeremybellEU, really sorry that I haven't followed through on this yet... just got really busy in my personal life in the last few weeks. I will find time tomorrow during the day to make sure I take a look at this. Thanks for following up!

**Comment by JeremybellEU** [comment]
Ah no problem. Personal life is more important, this issue isn't that major. Take your time!

**Comment by Yatser** [comment]
OK, I've updated JSTree in the latest release... the release will take a while to roll out but it's up there.

**Comment by JeremybellEU** [comment]
:+1: will look forward to it and hopefully it is solved!

**Comment by Yatser** [comment]
@JeremybellEU I'm going to close this issue, I think it's resolved, let me know otherwise :+1:
